name: 其他
description: 用于其他问题
body:
  - type: dropdown
    id: module
    attributes:
      label: 所属模块
      options:
        - 自强 Auth 前端
        - 自强 Auth 后端
        - 其他
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其他
      description: 其他问题
      placeholder: 描述您的问题
    validations:
      required: true